name: Build and Release

on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        files :
        - minc_darwin_amd64
        - minc_darwin_arm64
        - minc.exe
        - minc_linux_amd64
        - minc_linux_arm64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Build release binaries
        run: make release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.files }}
          path: out/release/${{ matrix.files }}
