name: Linux Test Docker

on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Build binary
        run: make install

      - name: Run minp cluster
        run: minc create cluster --provider docker --log-level debug