name: Windows Test Podman

on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-2025
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Build binary
        run: make install

      - name: update wsl in windows
        run: |
          wsl --update
          wsl --version

      - name: Create .wslconfig file to enable cgroupsv2
        run: |
          $wslConfigPath = "$env:UserProfile/.wslconfig"
          $content = "
          [wsl2]
          kernelCommandLine = cgroup_no_v1=all
          "
          Set-Content -Path $wslConfigPath -Value $content -Encoding UTF8
          Write-Output "File created: $wslConfigPath"
        shell: pwsh

      - name: Restart wsl
        run: wsl --shutdown

      - name: Get latest podman remote binary
        run: |
          curl -L -O https://github.com/containers/podman/releases/download/v5.1.1/podman-remote-release-windows_amd64.zip
          unzip podman-remote-release-windows_amd64.zip

      - name: Put podman binary to bin folder
        run: Copy-Item -Path .\podman-5.1.1\usr\bin\* -Destination $env:USERPROFILE\go\bin\ -Recurse
        shell: pwsh

      - name: Start the podman machine
        run: podman machine init --rootful --now

      - name: Run minp cluster
        run: |
          minc create --log-level debug
          podman stop microshift
          minc status
          minc create --log-level debug
          minc status

      - name: Install oc
        shell: bash
        run: |
          URL="https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable/openshift-client-windows.zip"
          FILENAME="openshift-client-windows.zip"
          echo "Downloading $URL"
          curl -H user-agent:minc-ci -L "$URL" -o "${FILENAME}" --max-time 300 --fail
          unzip -u "$FILENAME"

      - name: Put oc binary to bin folder
        run: Copy-Item -Path oc.exe -Destination $env:USERPROFILE\go\bin\ -Recurse
        shell: pwsh

      - name: Test if generate kubeconfig works as expected
        shell: bash
        run: |
          oc config get-contexts
          oc config delete-context microshift
          minc generate-kubeconfig
          oc config get-contexts
          oc get pods -A

      - name: Test the sample app
        run: |
          podman build -t quay.io/praveenkumar/myserver:v1 https://github.com/praveenkumar/simple-go-server.git
          oc apply -f https://raw.githubusercontent.com/praveenkumar/simple-go-server/refs/heads/main/kubernetes/deploy.yaml
          oc get pods -n demo
          oc wait --for=jsonpath='{.status.phase}'=Running pod/myserver -n demo
          oc expose svc myserver -n demo
          oc get routes -n demo
          curl -Ik myserver-demo.apps.127.0.0.1.nip.io:9080
